services:
  frontend:
    build: ./code-paste-frontend
    ports:
      - 80:3000
    networks:
      default:
        ipv4_address: 10.5.0.2
    depends_on:
      - client_backend

  notification_service:
    build: ./code-paste-backend/notification_service
    networks:
      default:
        ipv4_address: 10.5.0.4
    depends_on:
        - redis

  client_backend:
    build: ./code-paste-backend/client_backend
    networks:
      default:
        ipv4_address: 10.5.0.3
    depends_on:
        - postgres
        - redis
        - minio
    restart: on-failure:10

  minio:
    image: minio/minio
    volumes:
      - minio_storage:/minio/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    ports:
      - 9001:9001
    networks:
      default:
        ipv4_address: 10.5.0.5

  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=redisadmin
      - REDIS_USER=redisadmin
      - REDIS_USER_PASSWORD=redisadmin
    volumes:
      - ./redisdata:/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redisadmin", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      default:
        ipv4_address: 10.5.0.6

  postgres:
    build: ./postgresql
    ports:
      - 5435:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgre"
      POSTGRES_PASSWORD: "postgre"
    networks:
      default:
        ipv4_address: 10.5.0.7

  search_backend:
    build: ./code-paste-backend/search_backend
    networks:
      default:
        ipv4_address: 10.5.0.8

  elasticsearch:
    image: elasticsearch:7.16.1
    volumes:
      - ./elastic_search/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elastic_search/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "elastic"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: kibana:7.16.1
    volumes:
      - ./kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
    ports:
      - 3002:3002
      - "5601:5601"
    networks:
      - default

volumes:
  minio_storage: {}

networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1