port: 90
session-key: "ZkxmAqw4bx9QkoSdqngK1g=="
oauth: y0__xCyhfHjAxjB3RMg2ICJpRIrbf85Bk4g8CUJynhwWLHHgfxlPA
translate-folder-id: b1gu8n6diniorcm8n9gt
translate-url: https://translate.api.cloud.yandex.net/translate/v2/translate
iam-url: https://iam.api.cloud.yandex.net/iam/v1/tokens
notifications_service_address: "127.0.0.1:8081"
search_service_address: "127.0.0.1:8080"
minio-settings:
  endpoint: "51.250.40.56:9000"
  access-key-id: "minioadmin"
  secret-access-key: "minioadmin"
  use-ssl: false
redis-settings:
  address: "51.250.40.56:6379"
  password: "redisadmin"
  client-name: "redisadmin"
postgres-settings:
  host: "51.250.40.56"
  user: "postgre"
  password: "postgre"
  database-name: "CodePaste"
  