port: 90
session-key: "ZkxmAqw4bx9QkoSdqngK1g=="
minio-settings:
  endpoint: "84.252.133.175:9000"
  access-key-id: "minioadmin"
  secret-access-key: "minioadmin"
  use-ssl: false
redis-settings:
  address: "84.252.133.175:6379"
  password: "redisadmin"
  client-name: "redisadmin"
postgres-settings:
  host: "84.252.133.175"
  user: "postgre"
  password: "postgre"
  database-name: "CodePaste"
  