cluster.name: "code-paste"
network.host: 0.0.0.0 # Для корректной работы внутри контейнера

xpack.security.http.ssl.enabled: false
xpack.security.enabled: false
xpack.license.self_generated.type: basic
